### ISSUE TITLE
Remove hard-coded Mapbox API key, use the one from local.env instead

### ISSUE THREAD

**Issue by noahbrenner** [Hack4Eugene/SpeedUpAmerica#75]
The file `app/assets/javascripts/mapbox.coffee` currently uses a hard-coded Mapbox key, not the one defined in `local.env`, which is set as an environment variable. The key is defined on both **line 27** and **line 173** of `mapbox.coffee`. It's been there since the file was created.

**Comment by ryanrolds** [comment]
Fixed.

**Comment by noahbrenner** [comment]
@ryanrolds Has the fix been merged yet? I'm still seeing it hard-coded here:

* https://github.com/Hack4Eugene/SpeedUpAmerica/blob/master/app/assets/javascripts/mapbox.coffee#L27
* https://github.com/Hack4Eugene/SpeedUpAmerica/blob/master/app/assets/javascripts/mapbox.coffee#L124

I imagine we should be using the key from `local.env` instead of doing this.

**Comment by ryanrolds** [comment]
You're right. I thought was already fixed.

**Comment by ryanrolds** [comment]
https://github.com/Hack4Eugene/SpeedUpAmerica/pull/100

**Comment by ryanrolds** [comment]
Now it's fixed.
